/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, g++ 15.1.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
module ripple_adder(i_carry, i_data0, i_data1, o_sum, o_carry);
  wire [4:0] _0_;
  input i_carry;
  wire i_carry;
  input [3:0] i_data0;
  wire [3:0] i_data0;
  input [3:0] i_data1;
  wire [3:0] i_data1;
  output o_carry;
  wire o_carry;
  output [3:0] o_sum;
  wire [3:0] o_sum;
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd4),
    .Y_WIDTH(32'd5)
  ) _1_ (
    .A(i_data0),
    .B(i_data1),
    .Y(_0_)
  );
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd5),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd5),
    .Y_WIDTH(32'd5)
  ) _2_ (
    .A(_0_),
    .B({ 4'h0, i_carry }),
    .Y({ o_carry, o_sum })
  );
endmodule
