/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, g++ 15.1.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module ripple_adder(i_carry, i_data0, i_data1, o_sum, o_carry);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire [8:0] _060_;
  wire [8:0] _061_;
  wire [8:0] _062_;
  wire [8:0] _063_;
  wire [8:0] _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  input i_carry;
  wire i_carry;
  input [7:0] i_data0;
  wire [7:0] i_data0;
  input [7:0] i_data1;
  wire [7:0] i_data1;
  output o_carry;
  wire o_carry;
  output [7:0] o_sum;
  wire [7:0] o_sum;
  sky130_fd_sc_hd__nor2_1 _088_ (
    .A(_002_),
    .B(_010_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _089_ (
    .A(_002_),
    .B(_010_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _090_ (
    .A(_001_),
    .B(_009_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _091_ (
    .A(_001_),
    .B(_009_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _092_ (
    .A(_000_),
    .B(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _093_ (
    .A(_019_),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _094_ (
    .A(_018_),
    .B(_022_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _095_ (
    .A(_018_),
    .B(_021_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _096_ (
    .A(_003_),
    .B(_011_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _097_ (
    .A(_003_),
    .B(_011_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _098_ (
    .A(_024_),
    .SLEEP(_025_),
    .X(_026_)
  );
  sky130_fd_sc_hd__a22oi_1 _099_ (
    .A1(_001_),
    .A2(_009_),
    .B1(_002_),
    .B2(_010_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nor2_1 _100_ (
    .A(_017_),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__xnor2_1 _101_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor3_1 _102_ (
    .A(_018_),
    .B(_021_),
    .C(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _103_ (
    .A(_023_),
    .B(_029_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o31ai_1 _104_ (
    .A1(_017_),
    .A2(_025_),
    .A3(_027_),
    .B1(_024_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xor2_1 _105_ (
    .A(_004_),
    .B(_012_),
    .X(_032_)
  );
  sky130_fd_sc_hd__xnor2_1 _106_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__or4_1 _107_ (
    .A(_018_),
    .B(_021_),
    .C(_029_),
    .D(_033_),
    .X(_034_)
  );
  sky130_fd_sc_hd__xnor2_1 _108_ (
    .A(_030_),
    .B(_033_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__maj3_1 _109_ (
    .A(_004_),
    .B(_012_),
    .C(_031_),
    .X(_035_)
  );
  sky130_fd_sc_hd__xor2_1 _110_ (
    .A(_005_),
    .B(_013_),
    .X(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _111_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _112_ (
    .A(_034_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xor2_1 _113_ (
    .A(_034_),
    .B(_037_),
    .X(_056_)
  );
  sky130_fd_sc_hd__maj3_1 _114_ (
    .A(_005_),
    .B(_013_),
    .C(_035_),
    .X(_039_)
  );
  sky130_fd_sc_hd__xor2_1 _115_ (
    .A(_006_),
    .B(_014_),
    .X(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _116_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor3_1 _117_ (
    .A(_034_),
    .B(_037_),
    .C(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xnor2_1 _118_ (
    .A(_038_),
    .B(_041_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__maj3_1 _119_ (
    .A(_006_),
    .B(_014_),
    .C(_039_),
    .X(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _120_ (
    .A(_007_),
    .B(_015_),
    .X(_044_)
  );
  sky130_fd_sc_hd__xnor2_1 _121_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _122_ (
    .A(_042_),
    .SLEEP(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__xnor2_1 _123_ (
    .A(_042_),
    .B(_045_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__maj3_1 _124_ (
    .A(_007_),
    .B(_015_),
    .C(_043_),
    .X(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _125_ (
    .A(_008_),
    .B(_016_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _126_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xor2_1 _127_ (
    .A(_046_),
    .B(_049_),
    .X(_059_)
  );
  sky130_fd_sc_hd__maj3_1 _128_ (
    .A(_008_),
    .B(_016_),
    .C(_047_),
    .X(_050_)
  );
  sky130_fd_sc_hd__a21o_1 _129_ (
    .A1(_046_),
    .A2(_049_),
    .B1(_050_),
    .X(_051_)
  );
  sky130_fd_sc_hd__xor2_1 _130_ (
    .A(_000_),
    .B(_020_),
    .X(_052_)
  );
  assign _060_[8] = 1'h0;
  assign _061_[8] = 1'h0;
  assign { _062_[8], _062_[0] } = { _060_[7], _061_[0] };
  assign { _063_[8], _063_[0] } = { 1'h0, _060_[0] };
  assign _001_ = i_data0[0];
  assign _009_ = i_data1[0];
  assign _002_ = i_data0[1];
  assign _010_ = i_data1[1];
  assign _003_ = i_data0[2];
  assign _011_ = i_data1[2];
  assign _004_ = i_data0[3];
  assign _012_ = i_data1[3];
  assign _005_ = i_data0[4];
  assign _013_ = i_data1[4];
  assign _006_ = i_data0[5];
  assign _014_ = i_data1[5];
  assign _007_ = i_data0[6];
  assign _015_ = i_data1[6];
  assign _008_ = i_data0[7];
  assign _016_ = i_data1[7];
  assign o_sum[1] = _053_;
  assign o_sum[2] = _054_;
  assign o_sum[3] = _055_;
  assign o_sum[4] = _056_;
  assign o_sum[5] = _057_;
  assign o_sum[6] = _058_;
  assign o_sum[7] = _059_;
  assign o_carry = _051_;
  assign _000_ = i_carry;
  assign o_sum[0] = _052_;
endmodule
