.PHONY: all clean wrap clamp wave.vcd

WRAP_EN ?= 0

all: wave.vcd

clean:
	@if [ -f wave.vcd ]; then rm wave.vcd; fi
	@if [ -d obj_dir ]; then rm -rf obj_dir; fi

wave.vcd:
	verilator -Wall -cc --exe --build --trace -j 0 cntr_updn_flags.cpp cntr_updn_flags.v -GWIDTH=4 -GWRAP_EN=$(WRAP_EN) -GMAX_CNT=7 -GMIN_CNT=1
	./obj_dir/Vcntr_updn_flags
	mv wave.vcd dump_$(if $(filter 1,$(WRAP_EN)),wrap,clamp).vcd

wrap:
	$(MAKE) -f Makefile.ci WRAP_EN=1

clamp:
	$(MAKE) -f Makefile.ci WRAP_EN=0