/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, g++ 15.1.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module ripple_adder_prim(i_carry, i_data0, i_data1, o_sum, o_carry);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire \ADD_STAGE[0].u_full_adder.i_carry ;
  wire \ADD_STAGE[0].u_full_adder.i_data0 ;
  wire \ADD_STAGE[0].u_full_adder.i_data1 ;
  wire \ADD_STAGE[0].u_full_adder.o_carry ;
  wire \ADD_STAGE[0].u_full_adder.o_sum ;
  wire \ADD_STAGE[1].u_full_adder.i_carry ;
  wire \ADD_STAGE[1].u_full_adder.i_data0 ;
  wire \ADD_STAGE[1].u_full_adder.i_data1 ;
  wire \ADD_STAGE[1].u_full_adder.o_carry ;
  wire \ADD_STAGE[1].u_full_adder.o_sum ;
  wire \ADD_STAGE[2].u_full_adder.i_carry ;
  wire \ADD_STAGE[2].u_full_adder.i_data0 ;
  wire \ADD_STAGE[2].u_full_adder.i_data1 ;
  wire \ADD_STAGE[2].u_full_adder.o_carry ;
  wire \ADD_STAGE[2].u_full_adder.o_sum ;
  wire \ADD_STAGE[3].u_full_adder.i_carry ;
  wire \ADD_STAGE[3].u_full_adder.i_data0 ;
  wire \ADD_STAGE[3].u_full_adder.i_data1 ;
  wire \ADD_STAGE[3].u_full_adder.o_carry ;
  wire \ADD_STAGE[3].u_full_adder.o_sum ;
  wire [4:0] carry;
  input i_carry;
  wire i_carry;
  input [3:0] i_data0;
  wire [3:0] i_data0;
  input [3:0] i_data1;
  wire [3:0] i_data1;
  output o_carry;
  wire o_carry;
  output [3:0] o_sum;
  wire [3:0] o_sum;
  sky130_fd_sc_hd__xnor2_1 _33_ (
    .A(_06_),
    .B(_10_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__maj3_1 _34_ (
    .A(_06_),
    .B(_10_),
    .C(_05_),
    .X(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(_07_),
    .B(_11_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(_15_),
    .B(_16_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _37_ (
    .A(_05_),
    .B(_14_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__maj3_1 _38_ (
    .A(_07_),
    .B(_11_),
    .C(_15_),
    .X(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(_08_),
    .B(_12_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__maj3_1 _40_ (
    .A(_08_),
    .B(_12_),
    .C(_17_),
    .X(_19_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(_09_),
    .B(_13_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__maj3_1 _42_ (
    .A(_09_),
    .B(_13_),
    .C(_19_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(_19_),
    .B(_20_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_17_),
    .B(_18_),
    .Y(_02_)
  );
  assign \ADD_STAGE[0].u_full_adder.i_carry  = i_carry;
  assign \ADD_STAGE[0].u_full_adder.i_data0  = i_data0[0];
  assign \ADD_STAGE[0].u_full_adder.i_data1  = i_data1[0];
  assign \ADD_STAGE[1].u_full_adder.i_carry  = \ADD_STAGE[0].u_full_adder.o_carry ;
  assign \ADD_STAGE[1].u_full_adder.i_data0  = i_data0[1];
  assign \ADD_STAGE[1].u_full_adder.i_data1  = i_data1[1];
  assign \ADD_STAGE[2].u_full_adder.i_carry  = \ADD_STAGE[1].u_full_adder.o_carry ;
  assign \ADD_STAGE[2].u_full_adder.i_data0  = i_data0[2];
  assign \ADD_STAGE[2].u_full_adder.i_data1  = i_data1[2];
  assign \ADD_STAGE[3].u_full_adder.i_carry  = \ADD_STAGE[2].u_full_adder.o_carry ;
  assign \ADD_STAGE[3].u_full_adder.i_data0  = i_data0[3];
  assign \ADD_STAGE[3].u_full_adder.i_data1  = i_data1[3];
  assign carry = { \ADD_STAGE[3].u_full_adder.o_carry , \ADD_STAGE[2].u_full_adder.o_carry , \ADD_STAGE[1].u_full_adder.o_carry , \ADD_STAGE[0].u_full_adder.o_carry , i_carry };
  assign o_carry = \ADD_STAGE[3].u_full_adder.o_carry ;
  assign o_sum = { \ADD_STAGE[3].u_full_adder.o_sum , \ADD_STAGE[2].u_full_adder.o_sum , \ADD_STAGE[1].u_full_adder.o_sum , \ADD_STAGE[0].u_full_adder.o_sum  };
  assign \ADD_STAGE[1].u_full_adder.o_sum  = _01_;
  assign _07_ = i_data0[1];
  assign _11_ = i_data1[1];
  assign _06_ = i_data0[0];
  assign _10_ = i_data1[0];
  assign _05_ = i_carry;
  assign \ADD_STAGE[0].u_full_adder.o_sum  = _00_;
  assign _09_ = i_data0[3];
  assign _13_ = i_data1[3];
  assign \ADD_STAGE[3].u_full_adder.o_carry  = _03_;
  assign \ADD_STAGE[3].u_full_adder.o_sum  = _04_;
  assign _08_ = i_data0[2];
  assign _12_ = i_data1[2];
  assign \ADD_STAGE[2].u_full_adder.o_sum  = _02_;
endmodule
